config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'eatery/suppliers#new'
  
  get 'static_pages/about'
  
  devise_for :shops, controllers: {
    registrations: 'shops/registrations',
    sessions: 'shops/sessions'
  }

  # 飲食店画面
  namespace :eatery, path: '/' do
    resources :suppliers
    resources :items
    resources :actual_stocks, only: %i[index] do
      collection do
        post :bulk_update
      end
    end
    get 'order_stocks/index'
    post 'order_stocks/bulk_update'
    get 'proper_stocks/index'
    post 'proper_stocks/bulk_update'
  end

  # 管理画面あとで作らなきゃいけない
  namespace :admin, path: '/' do
  end
end

app/models/supplier.rb
# frozen_string_literal: true

class Supplier < ApplicationRecord
  belongs_to :shop
  has_many :items
  validates :name, presence: true
end

app/controllers/eatery/actual_stocks_controller.rb
# frozen_string_literal: true

class Eatery::ActualStocksController < Eatery::ApplicationController
  def index
    @target_date = params[:target_date] ? params[:target_date].to_date : Date.today
    @stock_form = ActualStockForm.new(current_shop: current_shop, target_date: @target_date)
  end

  def bulk_update
    @target_date = update_target_date
    @stock_form = ActualStockForm.new(current_shop: current_shop,
                                      target_date: @target_date,
                                      update_params: stock_collection_params)
    if @stock_form.save
      redirect_to eatery_actual_stocks_path(target_date: @target_date),
                  notice: '商品を登録しました。'
    else
      render :index
    end
  end

  private

  def update_target_date
    params
      .require(:actual_stock_form)
      .permit(:target_date)[:target_date]
  end

  def stock_collection_params
    params
      .require(:actual_stock_form)
      .permit(actual_stocks: %i[quantity sequence])[:actual_stocks]
  end
end

app/controllers/eatery/application_controller.rb
# frozen_string_literal: true

class Eatery::ApplicationController < ActionController::Base
  before_action :authenticate_shop!
end

app/controllers/eatery/items_controller.rb
# frozen_string_literal: true

class Eatery::ItemsController < Eatery::ApplicationController
  def index
    # TODO: paginationを追加する
    @items = current_shop.items
  end

  def new
    @item = current_shop.items.new
  end

  def create
    @item = current_shop.items.build(item_params)
    return render :new if @item.invalid?

    @item.lead_time ||= @item.supplier.lead_time
    if @item.save
      redirect_to eatery_items_path, notice: '登録しました'
    else
      render :new
    end
  end

  def edit
    @item = current_shop.items.find(params[:id])
  end

  def update
    @item = current_shop.items.find(params[:id])
    if @item.update(item_params)
      redirect_to eatery_items_path, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :supplier_id, :name, :category, :lead_time, :price, :memo
    ).merge(shop_id: current_shop.id)
  end
end

app/controllers/eatery/order_stocks_controller.rb
# frozen_string_literal: true

class Eatery::OrderStocksController < ApplicationController
  before_action :check_actual_stock

  def index
    @order_date = params[:order_date] ? params[:order_date].to_date : Date.today
    @order_collection = OrderFormCollection.new(registed_stock_items: @registed_stock_items, order_date: @order_date)
  end

  def bulk_update
    @order_date = params[:order_form_collection][:order_date].to_date
    @order_collection = OrderFormCollection.new(registed_stock_items: @registed_stock_items,
                                                order_date: @order_date,
                                                update_params: order_collection_params)
    if @order_collection.save
      redirect_to eatery_order_stocks_index_path(order_date: @order_date), notice: '登録しました'
    else
      render :index
    end
  end

  private

  def check_actual_stock
    @not_regist_stock_items = Item.load_not_regist_stock_items(current_shop)
    @registed_stock_items = current_shop.items.where.not(id: @not_regist_stock_items.map(&:id))
  end

  def order_collection_params
    params
      .require(:order_form_collection)
      .permit(order_forms: [:quantity])[:order_forms]
  end
end

app/controllers/eatery/proper_stocks_controller.rb
# frozen_string_literal: true

class Eatery::ProperStocksController < ApplicationController
  def index
    @proper_collection = ProperStockCollection.new(current_shop: current_shop)
  end

  def bulk_update
    @proper_collection = ProperStockCollection.new(current_shop: current_shop, update_params: proper_collection_params)
    if @proper_collection.save
      redirect_to eatery_proper_stocks_index_path, notice: '登録しました'
    else
      render :index
    end
  end

  private

  def proper_collection_params
    params
      .require(:proper_stock_collection)
      .permit(proper_stocks: [:quantity])[:proper_stocks]
  end
end

app/controllers/eatery/suppliers_controller.rb
# frozen_string_literal: true

class Eatery::SuppliersController < Eatery::ApplicationController
  def index
    # TODO: paginationを追加する
    @suppliers = current_shop.suppliers.all
  end

  def new
    @supplier = current_shop.suppliers.new
  end

  def create
    @supplier = current_shop.suppliers.build(supplier_params)

    if @supplier.save
      redirect_to eatery_suppliers_path, notice: '登録しました'
    else
      render :new
    end
  end

  def edit
    @supplier = current_shop.suppliers.find(params[:id])
  end

  def update
    @supplier = current_shop.suppliers.find(params[:id])

    if @supplier.update(supplier_params)
      redirect_to eatery_suppliers_path, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(
      :name, :tel, :fax, :email, :lead_time, :memo
    ).merge(shop_id: current_shop.id)
  end
end

app/helpers/eatery/order_stocks_helper.rb
# frozen_string_literal: true

module Eatery::OrderStocksHelper
end

app/helpers/eatery/proper_stocks_helper.rb
# frozen_string_literal: true

module Eatery::ProperStocksHelper
end

app/views/eatery/suppliers/_form.html.haml
- if f.object.errors.any?
  = render 'layouts/eatery/error_messages', errors: f.object.errors

.form-group
  = f.label :name, '仕入先名'
  = f.text_field :name, class: 'form-control', placeholder: '生鮮食品株式会社'
.form-group
  = f.label :tel, '電話番号'
  = f.text_field :tel, class: 'form-control', placeholder: '0123-456-789'
.form-group
  = f.label :fax, 'FAX'
  = f.text_field :fax, class: 'form-control', placeholder: '0123-456-789'
.form-group
  = f.label :email, 'メールアドレス'
  = f.text_field :email, class: 'form-control', placeholder: '0123-456-789'
.form-group
  = f.label :lead_time, '発注から到着までの日数'
  = f.number_field :lead_time, class: 'form-control', placeholder: '2'

.form-group
  = f.label :memo, 'メモ'
  = f.text_field :memo, class: 'form-control', placeholder: 'メモ'
= f.button '保存', type: 'submit', class: 'btn btn-success'

app/views/eatery/suppliers/edit.html.haml
%section
  %h1.title 仕入先編集

  = form_with model: @supplier, url: eatery_supplier_path, local: true do |f|
    = render 'form', f: f

app/views/eatery/suppliers/index.html.haml
%section
  %h1.title 仕入先一覧
  %hr

  = link_to ' 新規作成', new_eatery_supplier_path, class: 'btn btn-outline-success fas fa-plus'
  %table.table.is-bordered.is-hoverable
    %thead
      %tr
        %th ID
        %th 仕入先名
        %th 電話番号
        %th FAX
        %th メールアドレス
        %th 発注から到着までの日数
        %th メモ
        %th
    %tbody
      - @suppliers.each do |supplier|
        %tr
          %td= supplier.id
          %td= supplier.name
          %td= supplier.tel
          %td= supplier.fax
          %td= supplier.email
          %td= supplier.lead_time
          %td= supplier.memo
          %td= link_to '編集', edit_eatery_supplier_path(supplier)

app/views/eatery/suppliers/new.html.haml
%section
  %h1.title 仕入先登録
  %hr

  = form_with model: @supplier, url: eatery_suppliers_path, local: true do |f|
    = render 'form', f: f