config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'eatery/suppliers#new'
  
  get 'static_pages/about'
  
  devise_for :shops, controllers: {
    registrations: 'shops/registrations',
    sessions: 'shops/sessions'
  }

  # 飲食店画面
  namespace :eatery, path: '/' do
    resources :suppliers
    resources :items
    resources :actual_stocks, only: %i[index] do
      collection do
        post :bulk_update
      end
    end
    get 'order_stocks/index'
    post 'order_stocks/bulk_update'
    get 'proper_stocks/index'
    post 'proper_stocks/bulk_update'
  end

  # 管理画面あとで作らなきゃいけない
  namespace :admin, path: '/' do
  end
end

app/controllers/eatery/actual_stocks_controller.rb
# frozen_string_literal: true

class Eatery::ActualStocksController < Eatery::ApplicationController
  def index
    @target_date = params[:target_date] ? params[:target_date].to_date : Date.today
    @stock_form = ActualStockForm.new(current_shop: current_shop, target_date: @target_date)
  end

  def bulk_update
    @target_date = update_target_date
    @stock_form = ActualStockForm.new(current_shop: current_shop,
                                      target_date: @target_date,
                                      update_params: stock_collection_params)
    if @stock_form.save
      redirect_to eatery_actual_stocks_path(target_date: @target_date),
                  notice: '商品を登録しました。'
    else
      render :index
    end
  end

  private

  def update_target_date
    params
      .require(:actual_stock_form)
      .permit(:target_date)[:target_date]
  end

  def stock_collection_params
    params
      .require(:actual_stock_form)
      .permit(actual_stocks: %i[quantity sequence])[:actual_stocks]
  end
end

app/controllers/eatery/application_controller.rb
# frozen_string_literal: true

class Eatery::ApplicationController < ActionController::Base
  before_action :authenticate_shop!
end

app/controllers/eatery/items_controller.rb
# frozen_string_literal: true

class Eatery::ItemsController < Eatery::ApplicationController
  def index
    # TODO: paginationを追加する
    @items = current_shop.items
  end

  def new
    @item = current_shop.items.new
  end

  def create
    @item = current_shop.items.build(item_params)
    return render :new if @item.invalid?

    @item.lead_time ||= @item.supplier.lead_time
    if @item.save
      redirect_to eatery_items_path, notice: '登録しました'
    else
      render :new
    end
  end

  def edit
    @item = current_shop.items.find(params[:id])
  end

  def update
    @item = current_shop.items.find(params[:id])
    if @item.update(item_params)
      redirect_to eatery_items_path, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :supplier_id, :name, :category, :lead_time, :price, :memo
    ).merge(shop_id: current_shop.id)
  end
end

app/controllers/eatery/order_stocks_controller.rb
# frozen_string_literal: true

class Eatery::OrderStocksController < ApplicationController
  before_action :check_actual_stock

  def index
    @order_date = params[:order_date] ? params[:order_date].to_date : Date.today
    @order_collection = OrderFormCollection.new(registed_stock_items: @registed_stock_items, order_date: @order_date)
  end

  def bulk_update
    @order_date = params[:order_form_collection][:order_date].to_date
    @order_collection = OrderFormCollection.new(registed_stock_items: @registed_stock_items,
                                                order_date: @order_date,
                                                update_params: order_collection_params)
    if @order_collection.save
      redirect_to eatery_order_stocks_index_path(order_date: @order_date), notice: '登録しました'
    else
      render :index
    end
  end

  private

  def check_actual_stock
    @not_regist_stock_items = Item.load_not_regist_stock_items(current_shop)
    @registed_stock_items = current_shop.items.where.not(id: @not_regist_stock_items.map(&:id))
  end

  def order_collection_params
    params
      .require(:order_form_collection)
      .permit(order_forms: [:quantity])[:order_forms]
  end
end

app/controllers/eatery/proper_stocks_controller.rb
# frozen_string_literal: true

class Eatery::ProperStocksController < ApplicationController
  def index
    @proper_collection = ProperStockCollection.new(current_shop: current_shop)
  end

  def bulk_update
    @proper_collection = ProperStockCollection.new(current_shop: current_shop, update_params: proper_collection_params)
    if @proper_collection.save
      redirect_to eatery_proper_stocks_index_path, notice: '登録しました'
    else
      render :index
    end
  end

  private

  def proper_collection_params
    params
      .require(:proper_stock_collection)
      .permit(proper_stocks: [:quantity])[:proper_stocks]
  end
end

app/controllers/eatery/suppliers_controller.rb
# frozen_string_literal: true

class Eatery::SuppliersController < Eatery::ApplicationController
  def index
    # TODO: paginationを追加する
    @suppliers = current_shop.suppliers.all
  end

  def new
    @supplier = current_shop.suppliers.new
  end

  def create
    @supplier = current_shop.suppliers.build(supplier_params)

    if @supplier.save
      redirect_to eatery_suppliers_path, notice: '登録しました'
    else
      render :new
    end
  end

  def edit
    @supplier = current_shop.suppliers.find(params[:id])
  end

  def update
    @supplier = current_shop.suppliers.find(params[:id])

    if @supplier.update(supplier_params)
      redirect_to eatery_suppliers_path, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(
      :name, :tel, :fax, :email, :lead_time, :memo
    ).merge(shop_id: current_shop.id)
  end
end

app/helpers/eatery/order_stocks_helper.rb
# frozen_string_literal: true

module Eatery::OrderStocksHelper
end

app/helpers/eatery/proper_stocks_helper.rb
# frozen_string_literal: true

module Eatery::ProperStocksHelper
end

app/views/layouts/eatery/_error_messages.html.haml
.notification.is-warning
  %ul
    - errors.full_messages.each do |message|
      %li= message

app/views/layouts/eatery/_flash_message.html.haml
- flash.each do |key, value|@hoge
  %div{ class: flash_class(key) }
    - if value.is_a?(Array)
      %ul
        - value.each do |message|
          %li= message
    - else
      = value

app/views/layouts/eatery/_header.html.haml
%nav.navbar.navbar-expand-lg.border-bottom
  .navbar-brand
    = link_to 'Bistrowork', eatery_order_stocks_index_path, class: 'navbar-brand text-secondary'
  %ul.navbar-nav.mr-auto
  
  %ul.navbar-nav
    %li.nav-item.mr-3
      = link_to ' Bistroworkとは', static_pages_about_path, class: "far fa-question-circle"

  - unless shop_signed_in?
    %ul.navbar-nav
      %li.nav-item.mr-3
        = link_to ' サインアップ', new_shop_registration_path, class: "fas fa-user-plus"
      %li.nav-item.mr-3
        = link_to ' ログイン', new_shop_session_path, class: "fas fa-sign-in-alt"
          
  - if shop_signed_in?
    %ul.navbar-nav
      %li.nav-item.mr-3.text-right
        = link_to ' ログアウト', destroy_shop_session_path, method: :delete, class: "fas fa-sign-out-alt"
      %li.nav-item.mr-3.text-right
        = link_to ' ' + current_shop.name, edit_shop_registration_path, class: "fas fa-user"

app/views/layouts/eatery/_sidemenu.html.haml
.sidebar-sticky.p-3.bg-light
  %p
    発注管理
  %ul.nav.flex-column
    %li.nav-item
      = link_to ' 発注情報登録', eatery_order_stocks_index_path, class: 'nav-link fas fa-file'
    %li.nav-item
      = link_to ' 在庫状況登録', eatery_actual_stocks_path, class: 'nav-link fas fa-archive'
  %p
    マスタ情報管理
  %ul.nav.flex-column
    %li.nav-item
      = link_to ' 仕入先一覧', eatery_suppliers_path, class: 'nav-link fas fa-store-alt'
    %li.nav-item
      = link_to ' 食材一覧', eatery_items_path, class: 'nav-link fas fa-apple-alt'
    %li.nav-item
      = link_to ' 最適在庫数設定', eatery_proper_stocks_index_path, class: 'nav-link fas fa-boxes'

app/views/layouts/eatery/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Bistrowork|個人飲食店業務をより効率的に
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/eatery/header'
    .container_fluid
      .row
        .col-sm-2
          = render 'layouts/eatery/sidemenu'
        .col-sm-9.pt-3
          = render 'layouts/eatery/flash_message'
          = yield